### PR TITLE
catch cql exceptions per subject

### LINKED ISSUE #626: Allow evaluated subject errors to not prevent MeasureReport creation
# Description

When evaluating a Measure for a large quantity of Subjects and encounter an error during CQL evaluation, it throws a vague error that does not allow the user to understand where to fix a problem. It also prevents results to be rendered for non-error throwing subjects that have been processed as a part of the evaluation, meaning if I have one problem subject among 100k, it prevents all other results from being rendered.

This request is to amend Measure $evaluate & $evaluate-measure to return a MeasureReport for subjects evaluated that encountered an exception/error during CQL evaluation. This allows for larger evaluations to provide visibility of results to the user and indicate the problem resources that need to be investigated. 

# Proposed Solution

1. Update MeasureEvaluator class that executes CQL expressions per subject to capture 'Exception' in an [OperationOutcome](https://www.hl7.org/fhir/r4/operationoutcome.html) resource that indicates the 'subjectId' (like Patient/{id}) and error message encountered.

2. Update overall status of MeasureReport to 'Error' to indicate to end users that the MeasureReport contains known errors

3. Capture generated OperationOutcome resource in field MeasureReport.contained for each subject related error. 

# Repro Example

Run $evaluate-measure operation against a population of patients where one Patient's associated resource has an invalid period, like Encounter.period:

'''
"period": {
    "start": "2024-01-29T08:30:00-07:00",
    "end": "2024-01-28T08:30:00-07:00"
  }
'''

If I have a population of 5 Patients, but only one Patient has an invalid Resource with a period, the operation returns an error:

`org.opencds.cqf.cql.engine.exception.InvalidInterval: Invalid Interval - the ending boundary must be greater than or equal to the starting boundary.`

This doesn't inform the user about where to go to address the encountered issue and doesn't tell you any of the other successfully generated results.

### PR DESCRIPTION
**Pull request by Capt-Mac**
Closes #626

### CODE REVIEW

File: cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvaluator.java [hunk 1]
```diff
@@ -305,11 +305,20 @@ protected MeasureDef evaluate(
...
+            try {
+                EvaluationResult result = libraryEngine.getEvaluationResult(
+                        id, subjectId, null, null, null, null, zonedDateTime, context);
+                evaluateSubject(measureDef, subjectTypePart, subjectIdPart, subjectSize, type, result);
+            } catch (Exception e) {
+                // Catch Exceptions from evaluation per subject, but allow rest of subjects to be processed (if
+                // applicable)
+                var error = String.format("Exception for subjectId: %s, Message: %s", subjectId, e.getMessage());
+                // Capture error for MeasureReportBuilder
+                if (!error.isEmpty()) {
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvaluator.java:317]: Why the conditional logic?  You created the error String so it'll never be empty

File: cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvaluator.java [hunk 2]
```diff
@@ -305,11 +305,20 @@ protected MeasureDef evaluate(
...
-
-            evaluateSubject(measureDef, subjectTypePart, subjectIdPart, subjectSize, type, result);
+            try {
+                EvaluationResult result = libraryEngine.getEvaluationResult(
+                        id, subjectId, null, null, null, null, zonedDateTime, context);
+                evaluateSubject(measureDef, subjectTypePart, subjectIdPart, subjectSize, type, result);
+            } catch (Exception e) {
+                // Catch Exceptions from evaluation per subject, but allow rest of subjects to be processed (if
+                // applicable)
+                var error = String.format("Exception for subjectId: %s, Message: %s", subjectId, e.getMessage());
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/common/MeasureEvaluator.java:315]: Please add an error log including the Exception object itself.   Exception.getMessage() in many cases will contain insufficient context to investigate the error.

File: cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureReportBuilder.java [hunk 3]
```diff
@@ -187,6 +190,22 @@ private void validateReference(String reference) {
                 throw new InvalidRequestException("Invalid full reference: " + reference);
             }
         }
+
+        public void addOperationOutcomes() {
+            var errorMsgs = this.measureDef.errors();
+            for (var error : errorMsgs) {
+                this.addContained(createOperationOutcome(error));
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4MeasureReportBuilder.java:197]: No need for "this." when calling another method in a class

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeContinuousVariableTest.java [hunk 4]
```diff
@@ -108,28 +107,15 @@ void continuousVariableResourcePopulation() {
...
-                    .report();
-            fail("This should throw error");
-        } catch (UnsupportedOperationException e) {
-            assertTrue(e.getMessage()
-                    .contains("'continuous-variable' measure is missing required population: initial-population"));
-        }
+        given.when()
+                .measureId("ContinuousVariableBooleanMissingReqdPopulation")
+                .evaluate()
+                .then()
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeContinuousVariableTest.java:113]: Question:  are you expecting this operation to have a status of ERROR like the other tests?

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeCohortTest.java [hunk 5]
```diff
@@ -125,22 +115,14 @@ void cohortResourceIndividual() {
...
-                    .report();
-            fail("This should throw error");
-        } catch (UnsupportedOperationException e) {
-            assertTrue(e.getMessage()
-                    .contains("MeasurePopulationType: denominator, is not a member of allowed 'cohort' populations"));
-        }
+        given.when()
+                .measureId("CohortBooleanExtraInvalidPopulation")
+                .evaluate()
+                .then()
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeCohortTest.java:121]: Question:  are you expecting this operation to have a status of ERROR like the other tests?

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeCohortTest.java [hunk 6]
```diff
@@ -89,22 +87,14 @@ void cohortResourcePopulation() {
...
-                    .report();
-            fail("This should throw error");
-        } catch (UnsupportedOperationException e) {
-            assertTrue(e.getMessage()
-                    .contains("MeasurePopulationType: numerator, is not a member of allowed 'cohort' populations"));
-        }
+        given.when()
+                .measureId("CohortBooleanMissingReqdPopulation")
+                .evaluate()
+                .then()
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeCohortTest.java:93]: Question:  are you expecting this operation to have a status of ERROR like the other tests?

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeRatioTest.java [hunk 7]
```diff
@@ -186,34 +168,15 @@ void ratioResourceIndividual() {
...
-                    .up()
-                    .report();
-            fail("This should throw error");
-        } catch (UnsupportedOperationException e) {
-            assertTrue(
-                    e.getMessage()
-                            .contains(
-                                    "MeasurePopulationType: measure-population, is not a member of allowed 'ratio' populations"));
-        }
+        given.when()
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeRatioTest.java:171]: Question:  if you have 5 subjects and all 5 subjects result in an error, are you still expecting to return an OperationOutcome containing all 5 errors and never throw an Exception as before?

File: cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/encounter/female-1988-2-encounter-1.json [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+      "system": "http://snomed.info/sct",
+      "code": "32485007",
+      "display": "Hospital admission (procedure)"
+    } ]
+  } ],
+  "subject": {
+    "reference": "Patient/female-1988-2"
+  },
+  "period": {
+    "start": "2024-01-29T08:30:00-07:00",
```
Comment (lukedegruchy) [inline cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/measure/r4/MinimalMeasureEvaluation/tests/encounter/female-1988-2-encounter-1.json:21]: Suggestion:  Please add "invalid period" or something to that effect in the title of this file.   It's a shame you can't add comments to JSON because it's not obvious at first glance that this JSON contains an invalid period.

**Review by lukedegruchy — APPROVED** [review]

**Review by lukedegruchy — APPROVED** [review]

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeRatioTest.java (hunk 7 above)
Comment (Capt-Mac) [reply cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeRatioTest.java:171]: correct, because this may aggregate with MeasureReports that do complete

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeCohortTest.java (hunk 5 above)
Comment (Capt-Mac) [reply cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScoringTypeCohortTest.java:123]: yes, corrected
