### PR TITLE
466 bug fix for group level scoring def, and concurrent mod exception

### LINKED ISSUE #466: Care-Gaps Concurrent modification exception
There is a bug in this [method](https://github.com/cqframework/clinical-reasoning/blob/ae83f7114f756e7da32ac6e84c95883b265ac545/cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java#L321C5-L333C6) that causes Measures that only specify scoring on the group level or are missing an improvement notation on the measure resource to throw an exception.

Steps:
1. POST Measure: [ecqm-content-qicore-2024/bundles/measure/ColonCancerScreeningFHIR/ColonCancerScreeningFHIR-bundle.json at main · cqframework/ecqm-content-qicore-2024](https://github.com/cqframework/ecqm-content-qicore-2024/blob/main/bundles/measure/ColonCancerScreeningFHIR/ColonCancerScreeningFHIR-bundle.json) 
4. POST Data: [ecqm-content-qicore-2024/bundles/measure/ColonCancerScreeningFHIR/ColonCancerScreeningFHIR-files/tests-bf3f2c9a-a802-4522-8e38-d1c806e71483-bundle.json at main · cqframework/ecqm-content-qicore-2024](https://github.com/cqframework/ecqm-content-qicore-2024/blob/main/bundles/measure/ColonCancerScreeningFHIR/ColonCancerScreeningFHIR-files/tests-bf3f2c9a-a802-4522-8e38-d1c806e71483-bundle.json)

5. run `http://localhost:8000/Measure/$care-gaps?periodStart=2025-01-01&periodEnd=2025-12-31&subject=Patient/bf3f2c9a-a802-4522-8e38-d1c806e71483&status=closed-gap&status=open-gap&measureId=ColonCancerScreeningFHIR` 

Observed Results 
 ```{
"resourceType": "OperationOutcome",
"issue": [ {
"severity": "error",
"code": "processing",
"diagnostics": "HAPI-0389: Failed to call access method: java.util.ConcurrentModificationException"
} ]
}```

Expected results

Care-Gaps report with no error

### PR DESCRIPTION
**Pull request by Capt-Mac**
closes #466

### CODE REVIEW

File: cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java [hunk 1]
```diff
@@ -320,25 +315,18 @@ protected <T extends Resource> T addConfiguredResource(Class<T> resourceClass, S
...
     protected List<Measure> ensureMeasures(List<Measure> measures) {
         measures.forEach(measure -> {
-            if (!measure.hasScoring()) {
-                ourLog.info("Measure does not specify a scoring so skipping: {}.", measure.getId());
-                measures.remove(measure);
-            }
             if (!measure.hasImprovementNotation()) {
-                ourLog.info("Measure does not specify an improvement notation so skipping: {}.", measure.getId());
-                measures.remove(measure);
+                ourLog.info(
```
Comment (JPercival) [inline cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/measure/r4/R4CareGapsService.java:319]: thought: This is the type of validation we should push upstream. Then we can give specific feedback in an OperationOutcome about issues with the Measure. In general, we _don't_ want to be lenient with these type of requirements. In this particular case, the improvement notation flips the meaning of the Measure. Good means bad, bad means good.

**Review by JPercival — APPROVED** [review]
