### PR TITLE
Measurescorer bug fix

### LINKED ISSUE #400: MeasureScorer does not calculate population exclusions or exceptions correctly
Measure Scorer currently only scores the values within a group based on Numerator/Denominator, but does not take into account the removal of exceptions and exclusions. This means that MeasureScores that should be removing counts due to an exception or/and exclusion are not doing so and scores are inaccurately recorded in the MeasureReport

Observed behavior:
Measure Report with population scores of:
ip:2, den:2, den-except:0, den-exclu:1, num: 1 => 0.5

Expected behavior:
ip:2, den:2, den-except:0, den-exclu:1, num: 1 => 1.0
den - den-exception = total den

### PR DESCRIPTION
**Pull request by Capt-Mac**
closes #400

adding extensions to each group and/or stratum that calculates measureScore by accumulating values that match designed set logic for respective populations in a measureReport resource. 

https://build.fhir.org/ig/HL7/cqf-measures/measure-conformance.html#proportion-measure-scoring

Any existing logic that aggregates or scores based off of only numerator/denominator will need to be updated in order to calculate the measure-score accurately, especially where denominator exception cases are used.

### CODE REVIEW

**Review by barhodes — CHANGES_REQUESTED** [review]
All these .DS_Store files should not be added to the repo.

**Review by barhodes — APPROVED** [review]

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java [hunk 1]
```diff
@@ -84,6 +155,15 @@ MeasureReportGroupComponent group(MeasureReport measureReport, String id) {
...
+    public MeasureReport.MeasureReportGroupStratifierComponent getStratumById(
+            MeasureReport measureReport, String groupId, String stratifierId) {
+        var group = group(measureReport, groupId);
+        return group.getStratifier().stream()
+                .filter(g -> g.getId().equals(stratifierId))
+                .findFirst()
+                .get();
+    }
+
     public List<Measure> getMyMeasures() {
```
Comment (JPercival) [inline cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java:167]: question: does this work for Measures that have some other basis than "Patient"? Have we validated it works for encounters, as an example? How about cohort Measures?

**Review by JPercival — APPROVED** [review]

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java [hunk 2]
```diff
@@ -73,8 +90,62 @@ void testScore_error_noids() {
...
-        var e = assertThrows(IllegalArgumentException.class, () -> scorer.score(measureScoringDef, measureReport));
-        assertEquals("No MeasureScoring value set", e.getMessage());
+        scorer.score(measureScoringDef, measureReport);
+        // when denominator =0, no score should be added to report
+        assertNull(group(measureReport, "DataCompleteness").getMeasureScore().getValue());
+    }
+
+    @Test
+    void testScore_noExtension() {
+        var measureUrl = "http://content.alphora.com/fhir/uv/mips-qm-content-r4/Measure/multirate-noext";
```
[the remark this answers is not in the document]
Comment (Capt-Mac) [reply cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java:92]: only reason this should not render is if it is not able to score a denominator, in which case it wouldn't score it. I don't think an error is needed

File: cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java (hunk 1 above)
Comment (Capt-Mac) [reply cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java:159]: cohort measures should not apply because they don't calculate a measure score (no num or den), it does however add extensions still to the measureScore.group for cohorts. This should be removed

Comment (Capt-Mac) [reply cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java:159]: encounter measure like CMS111 has a test case and does not currently add the new extensions and does not calculate measureScore

Comment (Capt-Mac) [reply cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/MeasureScorerTest.java:159]: CMS111 is continuous variable, so like cohort, doesn’t apply to measureScoring

DischargedonAntithromboticTherapyFHIR is proportion using that same extension for encounter and does appropriately get scored using newly added logic.
